---
# Kubernetes deployment example using a Daemonset and labeled nodes.
# Label a node 'boilest':'worker' and Boilest will automatically deploy to it
# Respository here is Azure Container Registry (ARC) so 
kind: Daemonset
apiVersion: apps/v1
metadata:
  name: boilest
  labels:
    app: boilest
    boil: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boilest
  template:
    metadata:
      labels:
        app: boilest
    spec:
      containers:
        - name: boilest
          image: ghcr.io/goingoffroading/boilest-worker:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: boilestmedia
              mountPath: "/boil_watch"
      nodeSelector:
        boilest: worker
      nodeName: node101-desktop
      volumes:
        - name: boilestmedia
          nfs:
            server: SERVER_IP_HERE
            path: "/SERVER/PATH/HERE"