---
kind: Daemonset
apiVersion: apps/v1
metadata:
  name: boilest
  labels:
    app: boilest
    boil: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boilest
  template:
    metadata:
      labels:
        app: boilest
    spec:
      containers:
        - name: boilest
          image: TBD
          imagePullPolicy: Always
          volumeMounts:
            - name: boilestmedia
              mountPath: "/boil_watch"
      nodeSelector:
        boilest: worker
      imagePullSecrets:
      - name: azureacr
      nodeName: node101-desktop
      volumes:
        - name: boilestmedia
          nfs:
            server: SERVER_IP_HERE
            path: "/SERVER/PATH/HERE"